### ISSUE TITLE
对于BFC的理解

### ISSUE THREAD

**Issue by ZYuMing** [ZYuMing/blog#2]
# 何为BFC？

---

BFC(Block formatting context)直译为”块级格式化上下文”。它是一个独立的渲染区域，只有Block-level box参与， 它规定了内部的Block-level Box如何布局，并且与这个区域外部毫不相干。
跟BFC相关的概念有`Box`,`Formatting Conetxt`。

## Box

Box是CSS布局的基本单位,分为block-level box和inline-level box，不同类型的Box，会参与不同的Formating。
`block-level box`:当display为block, list-item, table的元素
`inline-level box`:当displayinline, inline-block, inline-table的元素 

## Formatting context

Formatting context是页面中的一块渲染区域，并且有一套渲染规则，决定其子元素将如何定位，以及其他元素的关系和相互作用。
常见的Formatting context的有Block fomatting context (简称BFC)和 Inline formatting context (简称IFC)。

# 触发BFC

*   根元素
*   float属性不为none;
*   position为absolute或fixed
*   display为inline-bolck,table-cell,table-caption,flex,inline-felx
*   overflow不为visible

# BFC规则

---

*   内部的Box会在垂直方向，一个一个地放置(也可以在水平方向)
*   Box的距离由margin决定，属于同一个BFC的两个相邻的Box的margin会发生重叠
*   每个元素的margin box的左边， 与包含块border box的左边相接触(对于从左往右的格式)。即使存在浮动也是如此
*   BFC的区域不会与float box重叠
*   BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素
*   计算BFC的高度时，浮动元素也参与计算

# BFC的用途

---

## 自适应两栏布局

利用BFC规则`BFC的区域不会与float box重叠`。触发右边的元素生成BFC，来实现两栏布局。
`HTML:`
```html
<body>
  <div class="aside"></div>
  <div class="main"></div>
</body>
```
`CSS:`
```css
html{
  height: 100%;
}
body{
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
}	
.aside{
  width: 300px;
  height: 100%;
  float: left;
  background: #f66;
}
.main{
  height: 100%;
  background: #fcc;
  overflow: hidden;
}
```

## 清除浮动

利用BFC规则`计算BFC的高度时，浮动元素也参与计算`。通过`overflow: hidden`触发父元素生成BFC
`HTML:`
```html
<div class="out">
  <div class="in1"></div>
  <div class="in2"></div>
</div>
```
`CSS:`
```css
.out{
  width: 500px;
  background-color: #666;
  overflow: hidden;
}
.in1{
  width: 100px;
  height: 100px;
  float: left;
  background-color: #999;
}
.in2{
  width: 100px;
  height: 100px;
  float: left;
  background-color: #ccc;
}
```
## 防止margin重叠

利用BFC规则`Box垂直方向的距离由margin决定。属于同一个BFC的两个相邻Box的margin会发生重叠算`，我们可以在一个元素外面包裹一层容器，并处罚金该容器生成一个BFC。则和相邻元素不属于同一个BFC，就不会发生margin重叠了。
`HTML:`
```html
<p>Haha</p>
<div class="wrap">
  <p>Hehe</p>
</div>
```
`CSS:`
```css
.wrap{
  overflow: hidden;
}
p{
  background-color: #333;
  width: 200px;
  margin: 100px;
}
```
